name: Run Trivy

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write
      security-events: write
      actions: read

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # Run Trivy vulnerability scanner
    - name: Run Trivy vulnerability scanner
      id: trivy-scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: llalondedkhub/log8100-webgoat:latest
        format: 'sarif'
        output: 'trivy-results.sarif'
        exit-code: '0'
        # severity: 'CRITICAL, HIGH'
        timeout: '15m'
        skip-files: '**/*.jar'
        limit-severities-for-sarif: true

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'